/**
 * server.js - Blink Share Backend
 * ------------------------------------
 * Node.js / Express middleware layer.
 * Handles file relay between browser and Shelby storage,
 * contract interaction, and link generation.
 *
 * Shelby API Key Notes:
 *   - The server-side private key (SHELBY_API_KEY) is loaded by shelby.js at startup
 *     and injected into ShelbyNodeClient at construction time.
 *   - Clients (browser) may optionally send their own client key via the
 *     X-Shelby-Client-Key header, which we validate format-only and log.
 *     This enables per-client usage tracking on the Geomi dashboard.
 *   - Acquire keys at https://geomi.dev -> API Resource
 *     Private key -> SHELBY_API_KEY in .env (server use)
 *     Client key  -> SHELBY_CLIENT_KEY in .env / frontend CONFIG (browser use)
 *
 * Routes:
 *   POST /api/upload           - receive encrypted file, push to Shelby
 *   GET  /api/download/:cid   - proxy encrypted blob from Shelby
 *   GET  /api/file/:fileId    - fetch on-chain metadata (via RPC)
 *   POST /api/verify/:fileId  - verify access (validate pw hash on-chain)
 *   DELETE /api/shelby/:cid   - signal early Shelby deletion
 *   GET  /api/health          - service health check
 */

require("dotenv").config();

const express     = require("express");
const multer      = require("multer");
const cors        = require("cors");
const helmet      = require("helmet");
const rateLimit   = require("express-rate-limit");
const { ethers }  = require("ethers");
const path        = require("path");
const crypto      = require("crypto");

const shelby      = require("./utils/shelby");
const enc         = require("./utils/encryption");

// Load contract ABI + address (generated by deploy script)
let contractInfo;
try {
  contractInfo = require("./contract.json");
} catch {
  contractInfo = { address: process.env.CONTRACT_ADDRESS || "0x0", abi: [] };
  console.warn("⚠️  contract.json not found — deploy the contract first.");
}

// ---------------------------------------------------------------------------
//  APP SETUP
// ---------------------------------------------------------------------------

const app  = express();
const PORT = process.env.PORT || 4000;

// Validate server-side API key format at startup
const SHELBY_API_KEY    = process.env.SHELBY_API_KEY    || "";
const SHELBY_CLIENT_KEY = process.env.SHELBY_CLIENT_KEY || ""; // optional frontend key

if (!SHELBY_API_KEY && process.env.SHELBY_MOCK !== "true") {
  console.warn(
    "\n[Server] WARNING: SHELBY_API_KEY not set.\n" +
    "          Get a private key at https://geomi.dev -> API Resource (Network: Testnet)\n" +
    "          Set it in .env as SHELBY_API_KEY=aptoslabs_***\n"
  );
} else if (SHELBY_API_KEY && !SHELBY_API_KEY.startsWith("aptoslabs_")) {
  console.warn("[Server] WARNING: SHELBY_API_KEY format unexpected (expected: aptoslabs_***).");
}

// ── Middleware ────────────────────────────────────────────────────────────────
app.use(helmet({
  crossOriginResourcePolicy: { policy: "cross-origin" },
}));

app.use(cors({
  origin : process.env.FRONTEND_URL || "http://localhost:3000",
  methods: ["GET", "POST", "DELETE"],
}));

app.use(express.json({ limit: "1mb" })); // metadata only - binary goes via multer

// ── Client API Key Middleware ─────────────────────────────────────────────────
// Reads the optional X-Shelby-Client-Key header forwarded from the browser.
// Validates format only -- actual auth is handled by ShelbyNodeClient (server key).
// Logs mismatched formats so misconfigured clients are easy to spot.
app.use((req, res, next) => {
  const clientKey = req.headers["x-shelby-client-key"];
  if (clientKey) {
    if (!clientKey.startsWith("aptoslabs_")) {
      console.warn(`[Server] Invalid client key format from ${req.ip} -- expected aptoslabs_***`);
    }
    // Attach to request for optional per-request logging / analytics
    req.shelbyClientKey = clientKey;
    req.shelbyNetwork   = req.headers["x-shelby-network"] || "testnet";
  }
  next();
});

// ── Rate limiting ─────────────────────────────────────────────────────────────
const uploadLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,  // 15 min
  max     : 20,               // 20 uploads per IP per 15 min
  message : { error: "Too many uploads. Please wait." },
});

const downloadLimiter = rateLimit({
  windowMs: 5 * 60 * 1000,
  max     : 60,
  message : { error: "Download rate limit exceeded." },
});

// ── Multer (memory storage — re-stream directly to Shelby) ────────────────────
const upload = multer({
  storage  : multer.memoryStorage(),
  limits   : { fileSize: parseInt(process.env.MAX_FILE_SIZE || "104857600") }, // 100 MB default
});

// ─────────────────────────────────────────────────────────────────────────────
//  ETHERS SETUP
// ─────────────────────────────────────────────────────────────────────────────

const provider = new ethers.JsonRpcProvider(
  process.env.RPC_URL || "http://127.0.0.1:8545"
);

let signer, contract;
if (process.env.BACKEND_PRIVATE_KEY) {
  signer   = new ethers.Wallet(process.env.BACKEND_PRIVATE_KEY, provider);
  contract = new ethers.Contract(contractInfo.address, contractInfo.abi, signer);
} else {
  // Read-only mode if no private key
  contract = new ethers.Contract(contractInfo.address, contractInfo.abi, provider);
  console.warn("⚠️  No BACKEND_PRIVATE_KEY set — running in read-only mode.");
}

// ─────────────────────────────────────────────────────────────────────────────
//  ROUTES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * GET /api/health
 * Returns service + Shelby node health.
 */
app.get("/api/health", async (req, res) => {
  const shelbyHealth = await shelby.health();
  res.json({
    status       : "ok",
    shelby       : shelbyHealth,
    contractAddr : contractInfo.address,
    timestamp    : Date.now(),
  });
});

// ─────────────────────────────────────────────────────────────────────────────

/**
 * POST /api/upload
 * Body: multipart/form-data
 *   - file           : encrypted binary blob (client encrypted with AES-256-GCM)
 *   - fileName       : original filename
 *   - mimeType       : MIME type
 *   - fileSizeKb     : original file size in KB
 *   - expirySeconds  : how long until expiry
 *   - txHash         : the on-chain upload transaction hash (for verification)
 *   - fileId         : the fileId emitted by the contract event
 *
 * Response: { cid, fileId, expiresAt, shareUrl }
 */
app.post("/api/upload", uploadLimiter, upload.single("file"), async (req, res) => {
  try {
    const { fileName, mimeType, fileSizeKb, expirySeconds, txHash, fileId } = req.body;

    if (!req.file) {
      return res.status(400).json({ error: "No file provided" });
    }
    if (!fileName || !mimeType || !fileSizeKb || !expirySeconds) {
      return res.status(400).json({ error: "Missing required metadata" });
    }

    const expiresAt = Math.floor(Date.now() / 1000) + parseInt(expirySeconds);

    // The file buffer is already encrypted by the client.
    // We just store it on Shelby as-is (opaque binary blob).
    const { cid, size, replicas } = await shelby.upload(
      req.file.buffer,
      fileName,
      mimeType,
      expiresAt
    );

    // Optionally verify the on-chain transaction (non-blocking)
    let onChainVerified = false;
    if (txHash) {
      try {
        const receipt = await provider.getTransactionReceipt(txHash);
        onChainVerified = receipt?.status === 1;
      } catch { /* non-fatal */ }
    }

    const shareUrl = buildShareUrl(fileId, req.headers.host);

    res.json({
      success         : true,
      cid,
      fileId,
      expiresAt,
      shareUrl,
      size,
      replicas,
      onChainVerified,
    });
  } catch (err) {
    console.error("[Upload]", err);
    res.status(500).json({ error: err.message || "Upload failed" });
  }
});

// ─────────────────────────────────────────────────────────────────────────────

/**
 * GET /api/download/:cid
 * Proxies the encrypted blob from Shelby to the client.
 * The client decrypts it locally using the key from the URL fragment.
 */
app.get("/api/download/:cid", downloadLimiter, async (req, res) => {
  try {
    const { cid } = req.params;

    if (!isValidCID(cid)) {
      return res.status(400).json({ error: "Invalid CID" });
    }

    const buffer = await shelby.download(cid);

    res.setHeader("Content-Type", "application/octet-stream");
    res.setHeader("Content-Length", buffer.length);
    res.setHeader("Cache-Control", "no-store");   // never cache encrypted content
    res.setHeader("X-Content-Type-Options", "nosniff");
    res.send(buffer);
  } catch (err) {
    console.error("[Download]", err);
    res.status(404).json({ error: "File not found or unavailable" });
  }
});

// ─────────────────────────────────────────────────────────────────────────────

/**
 * GET /api/file/:fileId
 * Fetches public on-chain metadata for a file.
 */
app.get("/api/file/:fileId", async (req, res) => {
  try {
    const { fileId } = req.params;

    if (contractInfo.abi.length === 0) {
      return res.status(503).json({ error: "Contract not configured" });
    }

    const meta = await contract.getFileMeta(fileId);

    res.json({
      owner            : meta.owner,
      fileName         : meta.fileName,
      mimeType         : meta.mimeType,
      expiresAt        : Number(meta.expiresAt),
      uploadedAt       : Number(meta.uploadedAt),
      fileSizeKb       : Number(meta.fileSizeKb),
      downloadCount    : Number(meta.downloadCount),
      passwordProtected: meta.passwordProtected,
      walletGated      : meta.walletGated,
      oneTimeLink      : meta.oneTimeLink,
      revoked          : meta.revoked,
      isExpired        : meta.isExpired,
    });
  } catch (err) {
    console.error("[File meta]", err);
    res.status(404).json({ error: "File not found" });
  }
});

// ─────────────────────────────────────────────────────────────────────────────

/**
 * POST /api/verify/:fileId
 * Body: { passwordHash?, walletAddress?, signature? }
 * Calls validateAccess on the smart contract and returns the result.
 * The backend acts as relayer here; actual enforcement is on-chain.
 */
app.post("/api/verify/:fileId", async (req, res) => {
  try {
    const { fileId }       = req.params;
    const { passwordHash, walletAddress, signature } = req.body;

    // Verify wallet signature if provided
    if (walletAddress && signature) {
      const message  = `Access request for file ${fileId}`;
      const recovered = ethers.verifyMessage(message, signature);
      if (recovered.toLowerCase() !== walletAddress.toLowerCase()) {
        return res.status(403).json({ error: "Invalid signature" });
      }
    }

    const hash = passwordHash || ethers.ZeroHash;

    // Simulate the call (read-only) to check if access would succeed
    // In production the client would call this directly via their wallet
    const canAccess = await contract.validateAccess.staticCall(fileId, hash, {
      from: walletAddress || ethers.ZeroAddress,
    }).catch(() => false);

    res.json({ canAccess });
  } catch (err) {
    console.error("[Verify]", err);
    res.status(403).json({ canAccess: false, error: err.message });
  }
});

// ─────────────────────────────────────────────────────────────────────────────

/**
 * DELETE /api/shelby/:cid
 * Signal Shelby to delete a blob early (called after on-chain revocation).
 * Only proceeds if the request includes a valid signed message.
 */
app.delete("/api/shelby/:cid", async (req, res) => {
  try {
    const { cid } = req.params;
    const { signature, walletAddress, fileId } = req.body;

    if (!signature || !walletAddress || !fileId) {
      return res.status(400).json({ error: "Missing signature / address / fileId" });
    }

    // Verify ownership via signed message
    const message  = `Revoke file ${fileId} cid ${cid}`;
    const recovered = ethers.verifyMessage(message, signature);
    if (recovered.toLowerCase() !== walletAddress.toLowerCase()) {
      return res.status(403).json({ error: "Invalid signature" });
    }

    // Verify on-chain that the file is indeed revoked/expired
    const meta = await contract.getFileMeta(fileId);
    if (!meta.revoked && !meta.isExpired) {
      return res.status(403).json({ error: "File not revoked on-chain" });
    }

    const deleted = await shelby.delete(cid);
    res.json({ deleted });
  } catch (err) {
    console.error("[Delete]", err);
    res.status(500).json({ error: err.message });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
//  HELPERS
// ─────────────────────────────────────────────────────────────────────────────

function buildShareUrl(fileId, host) {
  const protocol = process.env.HTTPS === "true" ? "https" : "http";
  const domain   = process.env.FRONTEND_URL || `${protocol}://${host}`;
  return `${domain}/d/${fileId}`;
}

function isValidCID(cid) {
  // Shelby CIDs: "shelby://..." or "shelby-mock-..." prefixed alphanumeric
  return typeof cid === "string" && /^[a-zA-Z0-9_:/.+-]{10,200}$/.test(cid);
}

// ─────────────────────────────────────────────────────────────────────────────
//  START
// ─────────────────────────────────────────────────────────────────────────────

app.listen(PORT, () => {
  const keyStatus = SHELBY_API_KEY
    ? `${SHELBY_API_KEY.slice(0, 14)}*** (authenticated)`
    : "NOT SET — anonymous mode";

  console.log(`\n🚀  Blink Share API running on port ${PORT}`);
  console.log(`    Contract     : ${contractInfo.address}`);
  console.log(`    Shelby key   : ${keyStatus}`);
  console.log(`    Shelby net   : ${process.env.SHELBY_NETWORK || "testnet"}`);
  console.log(`    Mode         : ${process.env.SHELBY_MOCK === "true" ? "🧪 MOCK" : "🌐 REAL"}`);
  console.log(`    Geomi docs   : https://geomi.dev/docs/api-keys\n`);
});

module.exports = app; // for testing
